version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cloudflare:
        patterns:
          - "wrangler"
          - "@cloudflare/*"
      drizzle:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      vike:
        patterns:
          - "vike"
          - "vike-*"
          - "@photonjs/*"
      three:
        patterns:
          - "three"
          - "@react-three/*"
          - "@types/three"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"
          - "autoprefixer"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
          - "vitest"
      hono:
        patterns:
          - "hono"
      og-image:
        patterns:
          - "satori"
          - "@resvg/*"
