name: Takaya Kobayashi
aka: Jigsaw, jgs, neo6120
copy: A Web Application/Service Creator
mainLinks:
  - name: Codes
    href: https://github.com/e-jigsaw
    fa: fab fa-github
  - name: Scrapbox
    href: https://scrapbox.io/jigsaw/
    fa: fas fa-sticky-note
links:
  - name: neo6120
    href: https://twitter.com/neo6120
    fa: fab fa-twitter-square
  - name: takaya.kobayashi
    href: http://fb.me/takaya.kobayashi
    fa: fab fa-facebook-square
  - name: takaya-kobayashi
    href: https://www.linkedin.com/in/takaya-kobayashi/
    fa: fab fa-linkedin
  - name: jgs
    href: https://dev.to/jgs
    fa: fab fa-dev
  - name: neo6120
    href: https://steamcommunity.com/id/neo6120
    fa: fab fa-steam
  - name: neo6120
    href: https://www.last.fm/user/neo6120
    fa: fab fa-lastfm-square
  - name: jigsaw
    href: https://bookmeter.com/users/81576
    fa: fas fa-book
  - name: jgs
    href: https://keybase.io/jgs
    fa: fas fa-key
projects:
  - name: 2 minutes starter
    href: https://2.kbys.tk
    desc: Just 2 minutes starter
  - name: status
    href: https://st.kbys.tk
    desc: Status my own
  - name: amp
    href: https://amp.kbys.tk
    desc: Generated from scrapbox
  - name: color
    href: https://color.kbys.tk
    desc: Random color code generator
  - name: emo
    href: https://emo.kbys.tk
    desc: Emoji search by Japanese
donates:
  monthly:
    - name: GitHub
      href: https://github.com/e-jigsaw
  onetime:
    - name: PayPal
      href: https://paypal.me/jgsw
    - name: Buy me a ramen
      href: https://www.buymeacoffee.com/jgsw
