packages:
  - packages/*

catalog:
  drizzle-orm: ^0.44.7
  hono: ^4.10.7
  react: ^19.2.0
  react-dom: ^19.2.0
  "@progfay/scrapbox-parser": ^10.0.2
  "@cloudflare/workers-types": ^4.20251128.0
  typescript: ^5.9.3
  vitest: ^4.0.14
  wrangler: ^4.54.0
  drizzle-kit: ^0.31.7

onlyBuiltDependencies:
  - workerd
